name: CustomItems
version: '${project.version}'
api-version: 1.18
main: com.mittenmc.customitems.CustomItems
depend: [ServerUtils]
softdepend: [RewardsInventory]
authors: [GavvyDizzle]
description: Custom item maker for Spigot
commands:
  customItems:
    aliases: [citems]
    description: Admin commands for CustomItems
    permission: customitems.admin
    permission-message: Insufficient permission
